#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# update
#
alias update='. ~/.zshrc'


#
# zshrc config
#
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
